[package]
name = "policy-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "policy_engine"
path = "src/lib.rs"

[dependencies]
nlu-core = { path = "../nlu-core" }
session-engine = { path = "../session-engine" }
