#!/usr/bin/env -S -i HOME=/var/empty PATH=/opt/homebrew/bin:/usr/bin:/bin LC_ALL=C LANG=C TZ=UTC /usr/bin/ruby --disable-gems
# frozen_string_literal: true

require_relative "p13-noise-evidence"

P13NoiseEvidence.run(ARGV)
