#!/usr/bin/env -S -i HOME=/var/empty PATH=/usr/bin:/bin LC_ALL=C LANG=C TZ=UTC /usr/bin/ruby --disable-gems
# frozen_string_literal: true

require_relative "validate-p02-v2"

P02V2Validation::CLI.run(ARGV)
