#!/usr/bin/env -S -i HOME=/var/empty PATH=/usr/bin:/bin LC_ALL=C LANG=C TZ=UTC /usr/bin/ruby --disable-gems
# frozen_string_literal: true

require_relative "p13-rustc-driver"

begin
  P13RustcDriver.run(ARGV)
rescue P13RustcDriver::Failure => error
  warn error.message
  exit 1
end
