#!/usr/bin/env -S -i HOME=/var/empty PATH=/usr/bin:/bin LC_ALL=C LANG=C TZ=UTC /usr/bin/ruby --disable-gems
# frozen_string_literal: true

require_relative "p14-rustc-driver"

begin
  P14RustcDriver.run(ARGV)
rescue P14RustcDriver::Failure => error
  warn error.message
  exit 1
end
