#!/usr/bin/env -S -i HOME=/var/empty PATH=/usr/bin:/bin LC_ALL=C LANG=C TZ=UTC /usr/bin/ruby --disable-gems
# frozen_string_literal: true

require_relative "validate-p14"

begin
  P14Validation.run(ARGV)
rescue P14Validation::Failure => error
  warn "P14_GATE_FAIL: #{error.message}"
  exit 1
end
